import {StyleSheet} from 'react-native';
import * as Colors from '../../res/values/colors';
import * as Fonts from '../../res/values/fonts';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f6f6f6',
  },
  backgroundView: {
    height: 200,
    width: '100%',
    backgroundColor: Colors.Green,
    borderBottomLeftRadius: 50,
    borderBottomRightRadius: 50,
    position: 'absolute',
    top: 0,
  },
  backArrowIcon: {
    height: 35,
    width: 35,
    margin: 10,
    tintColor: Colors.White,
  },
  profilContainer: {
    height: 300,
    width: '95%',
    backgroundColor: Colors.White,
    alignSelf: 'center',
    marginHorizontal: 10,
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    borderRadius: 20,
  },
  imageContainer: {
    height: 120,
    width: 120,
    backgroundColor: Colors.White,
    alignSelf: 'center',
    borderRadius: 70,
    marginTop: -50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  doctorImage: {
    height: 110,
    width: 110,
  },
  primeText: {
    fontFamily: Fonts.SemiBold,
    color: Colors.Blue,
    position: 'absolute',
    margin: 20,
  },
  ratingContainer: {
    flexDirection: 'row',
    position: 'absolute',
    right: 0,
    margin: 20,
  },
  starIcon: {
    height: 15,
    width: 15,
    tintColor: 'yellow',
  },
  rating: {
    color: Colors.GrayDark,
    marginLeft: 5,
  },
  nameText: {
    alignSelf: 'center',
    fontSize: 18,
    fontFamily: Fonts.SemiBold,
    color: Colors.GrayDark,
  },
  desText: {
    alignSelf: 'center',
    fontFamily: Fonts.SemiBold,
    color: Colors.GrayMedium,
    marginTop: -10,
    marginBottom: 5,
  },
  expContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
  },
  boldText: {
    fontFamily: Fonts.SemiBold,
  },
  normalText: {
    fontFamily: Fonts.SemiBold,
    color: Colors.GrayMedium,
  },
  imagesContainer: {
    flexDirection: 'row',
    marginHorizontal: 20,
    alignSelf: 'center',
  },
  image: {
    height: 80,
    width: 80,
    margin: 10,
    borderRadius: 10,
  },
  contentContainer: {
    flex: 1,
    justifyContent: 'space-around',
    marginVertical: 10,
  },
  bottomButtonContainer: {
    height: 50,
    width: '95%',
    alignSelf: 'center',
    borderRadius: 30,
    position: 'absolute',
    bottom: 10,
    backgroundColor: Colors.White,
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  bookButton: {
    width: '50%',
    height: '100%',
    backgroundColor: Colors.Green,
    borderRadius: 30,
    position: 'absolute',
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookText: {
    fontSize: 16,
    fontFamily: Fonts.SemiBold,
    color: Colors.White,
  },
  feedBackConatainer: {
    width: '50%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.White,
    borderRadius: 30,
  },
  feedbackText: {
    fontSize: 16,
    fontFamily: Fonts.Regular,
  },
  bottomContainer: {
    width: '95%',
    flex: 1,
    // height: 100,
    backgroundColor: Colors.White,
    alignSelf: 'center',
    borderRadius: 20,
    marginTop: 20,
    borderWidth: 2,
    borderColor: Colors.WhiteSmoke,
  },
  feesContainer: {
    height: 45,
    borderBottomWidth: 0.5,
    width: '90%',
    flexDirection: 'row',
    borderColor: Colors.GrayDim,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  feeText1: {
    fontFamily: Fonts.SemiBold,
    color: Colors.GrayLight,
  },
  feeText2: {
    fontFamily: Fonts.SemiBold,
    color: Colors.GrayDark,
  },
  bookButtonSmall: {
    height: 30,
    width: 100,
    borderWidth: 1,
    borderColor: Colors.Green,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bookButtonSmallText: {
    fontFamily: Fonts.SemiBold,
    color: Colors.Green,
  },
  timeContainer: {
    height: 45,
    width: '90%',
    borderBottomWidth: 0.5,
    borderColor: Colors.GrayDim,
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  timeText1: {
    fontFamily: Fonts.SemiBold,
    color: 'red',
    fontSize: 12,
  },
  timeText2: {
    fontFamily: Fonts.SemiBold,
    color: Colors.GrayDark,
    fontSize: 12,
  },
  timeText3: {
    fontFamily: Fonts.SemiBold,
    color: Colors.Green,
    fontSize: 12,
  },
  addressText: {
    alignSelf: 'center',
    marginTop: 10,
    fontFamily: Fonts.SemiBold,
    color: Colors.GrayLight,
    fontSize: 12,
  },
  mapImage: {
    height: 120,
    width: '90%',
    alignSelf: 'center',
    borderRadius: 10,
    marginTop: 10,
  },
  line: {
    height: 1,
    width: '90%',
    backgroundColor: Colors.GrayDim,
    alignSelf: 'center',
    marginTop: 20,
  },
  feedbackHeading: {
    fontSize: 16,
    marginLeft: 20,
    color: Colors.GrayLight,
    fontFamily: Fonts.SemiBold,
  },
  feedBack: {
    marginLeft: 20,
    fontFamily: Fonts.Regular,
    color: Colors.GrayDark,
  },
  allServicesHeading: {
    fontSize: 14,
    marginLeft: 20,
    color: Colors.Blue,
    fontFamily: Fonts.SemiBold,
  },
  varificationContainer: {
    flexDirection: 'row',
    marginLeft: 20,
    alignItems: 'center',
    marginTop: 10,
  },
  verifiedRound: {
    height: 15,
    width: 15,
    borderRadius: 30,
    backgroundColor: Colors.Green,
  },
});
